name: EmptyInventory
main: yetanotherx.bukkitplugin.EmptyInventory.EmptyInventory
version: 1.0
commands:
    empty:
        description: Erase your inventory. Use -all to clean the hotbar too.
        usage: /<command> [-all]